### PR TITLE
Add some BMM requested packages

### PR DESCRIPTION
**Pull request by leofang**
Address #31. It seems all of the added packages are cross-platform. The rest 3 packages `lmfit`, `h5py`, and `sklearn` are already present. I have not added `slack_sdk` yet, as I have no idea what's that for...

### CODE REVIEW

**Comment by leofang** [comment]
I was following https://nsls-ii-forge.github.io/docs/creating_packages.html#rerender-the-feedstock and did`conda smithy rerender --feedstock_directory . -e recipe/conda_build_config.yaml`, but it by default falls back to NumPy 1.11 -- is this wanted?

**Comment by leofang** [comment]
> it by default falls back to NumPy 1.11 -- is this wanted?

Looks like it's OK. This information is not really used. This PR is ready I think.

**Review by jklynch — APPROVED** [review]
I checked the numpy version as well and it is 1.19.

**Comment by leofang** [comment]
Thanks @jklynch!

**Comment by mrakitin** [comment]
> I was following https://nsls-ii-forge.github.io/docs/creating_packages.html#rerender-the-feedstock and did `conda smithy rerender --feedstock_directory . -e recipe/conda_build_config.yaml`, but it by default falls back to NumPy 1.11 -- is this wanted?

I think we with @jklynch had to add the extra flag `-e ...` when we encountered an issue earlier this year. Conda-smithy fixed the problem since then, so it's not needed anymore. I'll submit a correction to the documentation. Now we need to copy the `conda_build_config.yaml` from the `event-model-feedstock` repo (with the extension of the used Python versions).

**Pull request merged**
