### PR TITLE
More analysis dependencies

### PR DESCRIPTION
**Pull request by mrakitin**
All non-NSLS-II dependencies (i.e., no packages like `chxtools`, `csxtools`, ...).

### CODE REVIEW

**Comment by mrakitin** [comment]
OK, it's good for now. Current limitations:
- I had to down-pin h5py to `>=2.8` (which made `hdf5` 1.10.2) to allow installation of `tomopy` -> `libopencv`, which wasn't built for newer versions of `hdf5` (e.g., 1.10.4) in the `defaults` channel.
- `pyxrf`'s dependency `h5py` was downgraded to `>=2.8` too to preserve `tomopy`.
- `tomopy` has some weird conflict for MacOS and Python 3.7, so I had to exclude this platform for tomopy
  - Windows builds started having some weird issue with `git`, trying to solve it via https://github.com/nsls-ii-forge/tomopy-feedstock/pull/3.

I implemented a small script which checks the packages' channels as well as performs checks of versions of specific packages (currently, `bluesky`, `ophyd`, and `databroker`). We should make it a package and reuse for other packages.

We discussed it with @dmgav regarding the `pyxrf` bullet point, and agreed he will try to perform a manual installation of `h5py` from PyPI to work-around the issue before a proper `libopencv` package appears in the `defaults` channel. Dmitri, do you mind to try it after this version of the metapackage is built/uploaded? Thanks!

**Comment by dmgav** [comment]
`conda create -n test analysis==2020C2.0=py37h5ca1d4c_1 python=3.7 tomopy -c nsls2forge -c defaults --override-channels`

Seems to work fine.

**Comment by mrakitin** [comment]
Thanks for checking, @dmgav! I think you even don't need to specify `tomopy` here as it's a part of the dependencies now.

**Comment by dmgav** [comment]
Yes, I forgot to delete `tomopy` from the command line. The following is the right command.

`conda create -n test analysis==2020C2.0=py37h5ca1d4c_1 python=3.7 -c nsls2forge -c defaults --override-channels`

**Pull request merged**
