### PR TITLE
Support xls files

### PR DESCRIPTION
**Pull request by mrakitin**
I added a test `.xls` file from SST (significantly shortened/blanked any user-related IDs). I intentionally did not add the `xlrd` package to see how pandas handles it without the package installed (we already have the `openpyxl` for operations on the `.xlsx` files). Once the tests fail, I'll try adding the missing libraries.

TODO: add both `xlrd` and `xrwt` packages.

### CODE REVIEW

**Comment by leofang** [comment]
Debugging...

**Comment by leofang** [comment]
> ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

**Comment by mrakitin** [comment]
> > ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

Yes, that's what the test was designed for. We want to confirm it fails, and then add the missing libs. Thanks!

**Comment by leofang** [comment]
linux is happy now, but I am not so sure about osx...

**Comment by leofang** [comment]
@mrakitin OS X finished after 4 hrs!!!

**Comment by mrakitin** [comment]
> @mrakitin OS X finished after 4 hrs!!!

@leofang, not bad! 😆

**Comment by mrakitin** [comment]
Thanks a lot for your help with this, @leofang!

**Comment by leofang** [comment]
My pleasure! This one was not too hard.

**Pull request merged**
